### ISSUE TITLE
Build against conduit 1.1

### ISSUE THREAD

**Issue by ocharles** [yesodweb/authenticate#31]
`conduit-1.1` no longer includes `Data.Conduit.Blaze` - it looks like you need to depend on `conduit-extra`.

**Comment by snoyberg** [comment]
@ocharles I think this issue can be safely closed now, correct?

**Comment by ocharles** [comment]
I think so, can always re-open if I still find there is a problem somewhere.

**Comment by snoyberg** [comment]
Wow, that was fast :)

**Comment by ocharles** [comment]
Eventually, you become one with Github ;)
