### ISSUE TITLE
authenticate URI and obtaining oauth_token from Credential

### ISSUE THREAD

**Issue by BartAdv** [yesodweb/authenticate#44]
Hello,

Most likely I'm missing something, but I think API lacks few helpers.

I'm trying to use it to authenticate via twitter, hence:

```haskell
oauthTwitter :: OAuth
oauthTwitter = newOAuth
               { oauthServerName = "api.twitter.com"
               , oauthRequestUri      = "https://api.twitter.com/oauth/request_token"
               , oauthAccessTokenUri  = "https://api.twitter.com/oauth/access_token"
               , oauthAuthorizeUri    = "https://api.twitter.com/oauth/authorize"
               , oauthSignatureMethod = HMACSHA1
               , oauthConsumerKey = "<snip>" 
               , oauthConsumerSecret = "<snip!>"
               , oauthVersion         = OAuth10a }

main = do
  mgr <- newManager tlsManagerSettings
  cred <- getTemporaryCredential oauthTwitter mgr
  let token = lookup "oauth_token" $ unCredential cred
  -- and now, use this token to generate api/oauth/authenticate?oauth_token=.... URL for the browser
```

So, in last two lines I'm doing raw lookup to grab the token, and then raw concatenation to generate URL (I rather use a helper akin to that of `authorizeUrl` to generate it for me). Am I correct in thinking that something like this could be added to the API?

**Comment by snoyberg** [comment]
Although I'm one of the maintainers of this library now, I have to profess ignorance in that I don't use it, just keep the code building. @meteficha may have more insight than I do. But if you'd find this kind of API useful, it seems like a good thing to add, and a PR would be welcome. If you're actively using this library and want to continue to contribute, joining as a comaintainer would be great as well :)

**Comment by meteficha** [comment]
I've actually never used the library in this fashion :).  If it works for you, send a PR.

**Comment by BartAdv** [comment]
Well, I've never used this library at all, and never used OAuth too. Will
see what's more will be needed once I get signing working

**Comment by BartAdv** [comment]
I am closing this for now. If anything worthwhile occurs - I'll send a PR.
