### ISSUE TITLE
License mismatch between Cabal and LICENSE file in authenticate

### ISSUE THREAD

**Issue by peti** [yesodweb/authenticate#46]
The Cabal file at https://github.com/yesodweb/authenticate/blob/master/authenticate/authenticate.cabal#L3 says `BSD3`, but the license file at https://github.com/yesodweb/authenticate/blob/master/authenticate/LICENSE contains a BSD2 license.

**Comment by snoyberg** [comment]
Thanks for the report, both locations are updated to the MIT license which the rest of the Yesod project uses.
