### ISSUE TITLE
`getAccessToken` returns extra fields

### ISSUE THREAD

**Issue by nomeata** [yesodweb/authenticate#49]
When trying to use this to authenticate with Twitter using the sample code here https://github.com/himura/twitter-conduit/blob/master/sample/simple.hs it fails.

The problem seems to be that the `Credential` returned by `getAccessToken` contains extra fields:
```
Credential {unCredential = [("oauth_token","XXX"),("oauth_token_secret","YYY"),("user_id","51459324"),("screen_name","nomeata")]}
```
and using these credentials later fails. I have to remove them using code like this
```
    let cred' = filter (\(k,v) -> k /= "user_id" && k /= "screen_name") cred
```
to make it work.

I am not sure if Twitter, `authenticate-oauth` or `twitter-conduit` is to blame, but somewhere something goes wrong…

Realted: https://github.com/himura/twitter-conduit/issues/64

**Comment by snoyberg** [comment]
I'm not seeing how this would be a bug in `authenticate`. Is there some guarantee in the docs or elsewhere that no additional fields will be returned?

**Comment by nomeata** [comment]
I am pretty ignorant about how these things should play together. Maybe extra fields should be ignored when authenticating further requests with it?

But if this is clearly not a but here, feel free to close.
