### ISSUE TITLE
Relax upper bound of RSA

### ISSUE THREAD

**Issue by mrkkrp** [yesodweb/authenticate#50]
See here: https://github.com/GaloisInc/RSA/issues/17#issuecomment-541806132. It should be `< 2.5` now to build with GHC 8.8.1.

**Comment by snoyberg** [comment]
I assume you're referring to `authenticate-oauth`, not `authenticate`, correct? Pinging @konn

**Comment by mrkkrp** [comment]
Ping. The change is really simple, if @konn is not available, I guess we could just bump it and that's it.

**Comment by snoyberg** [comment]
I wouldn't be able to make a release to Hackage.

**Comment by konn** [comment]
Sorry for late reply (I assumed I've already resigned the maintainer of this package).
I will release it on Hackage shortly.
If I remember correctly, I've already given a maintainer access for Hackage to @snoyberg, @meteficha , @mlitchard and @achirkin. Is there anything missing that I have to make release more flexible?

**Comment by snoyberg** [comment]
My mistake, I must have checked the wrong package. I'll take care of future bounds relaxations then.
